name: Sidelobe Build Matrix Linux
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Linux, ${{matrix.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx:
          #- g++-7
          - g++-10
        build_type: [Release]
        std: [14]
        include:
          #- cxx: g++-7
          #  other_pkgs: g++-7
          - cxx: g++-10
            other_pkgs: g++-10
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup & Cmake
      working-directory: deploy
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              ../..
        
    - name: Build & Run Tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: deploy/build
      run: |
        cmake --build . --parallel 2
        ctest -C ${{ matrix.build_type }} -L AudioTraitsTest -j 2
